!pragma layout smetana
@startuml "Создание стиля"

title "Создание стиля"

actor user as "Пользователь"
participant web as "Веб-севис"
participant llm as "Внешняя ЯМ"
participant embed as "Генератор\nэмбеддингов"
participant vdb as "Веторная БД"
participant db as "Каталог"

user -> web : Запрос на создание стиля

  activate web
  
    activate llm
    
      web -> llm : Отправка промпта и контекста к нему
      llm --> web : Ключевые токены для подбора одежды

      web -> embed : Текст для генерации эмбеддингов

      embed -> embed : Генерация эмбеддингов
      activate vdb
      embed -> vdb : Векторный поиск по эмбеддингам
      vdb --> embed : Список векторов (ИД, метаданные)
      deactivate vdb
      
      embed --> web : Нормализованный список товаров с объяснением
      
      loop пока не найдётся подходящий образ\nиз имеющейся в каталоге одежды
          web -> db : Поиск одежды по эмбеддингам
          activate db
          alt товар найден
            db --> web : Данные товара и ссылка
          else товар отсутствует
            db --> web : Ошибка об отсутствии товара
            deactivate db
          end
      end
    
    deactivate llm
    
    web --> user : Отображение образов и описания к ним
  
  deactivate web

@enduml