@startuml "Подборочка"
'left to right direction

actor "Пользователь" as User
actor "Партнёр" as Partner
actor "«Подборочка»" as System #white

' --- Блок: Приём и анализ данных ---
usecase "Загрузка\nданных пользователя" as UC1
'usecase "Анализ\nизображений" as UC2
'usecase "Формирование\nстилевого профиля" as UC3

' --- Блок: Поиск одежды ---
usecase "Создание стиля" as UC4
usecase "Поиск\nэлементов одежды" as UC4_1
usecase "Фильтрация\nпо стилю и условиям" as UC5
usecase "Обработка\nнерелевантных запросов" as UC6
usecase "Заполнение каталога\nодежды" as UC21

' --- Блок: Консультации ---
usecase "Стилевые\nконсультации" as UC4_2
usecase "Предупреждение\nоб опасных рекомендациях" as UC9

' --- Блок: Визуализация ---
usecase "Визуализация\nобразов" as UC10

' --- Маскот ---
usecase "Отображение\nмаскота" as UC13
'usecase "Выбор одежды\nмаскота" as UC15
usecase "Скрытие/отображение\nмаскота" as UC16

' --- Реклама и партнёры ---
usecase "Реферальные\nпереходы" as UC18
usecase "Учёт\nреферальных покупок" as UC19

' --- Безопасность ---
usecase "Защита\nперсональных данных" as UC20

' --------------------------------------
' Связи акторов с Use Cases
' --------------------------------------

' Пользователь
User --> UC1
User ---> UC4
UC4 <|- UC4_2
UC4 <|-l- UC4_1
User --> UC10
User --> UC16
User ---> UC18

' Партнёр
Partner .l.> UC21 : <<включ.>>
Partner .d.> UC19 : <<включ.>>
Partner .u..> UC18 : <<включ.>>

' Система (внутренние процессы)
System -u--> UC5
System -u--> UC6
System -u--> UC9
System -l-> UC13
System -> UC21
System -u-> UC20
System -r-> UC19

UC4 ..> UC5 : <<включ.>>
UC4 ..> UC6 : <<включ.>>
UC4 ..> UC9 : <<включ.>>
UC10 .r..> UC4 : <<дополн.>>

@enduml