!pragma layout smetana
@startuml "Создание стиля"

title "Создание стиля"

actor user as "Пользователь"

participant app as "Веб-приложение"
participant web as "Веб-севис"
participant neural as "Неиронная\nсеть"
participant db as "Каталог"
participant llm as "Внешняя ЯМ"

user -> web : Запрос на создание стиля

  activate web
  
    activate llm
    
      web -> llm : Отправка промпта и контекста к нему
      llm --> web : Ключевые токены для подбора одежды
      
      web -> neural : Запрос на подбор одежды по токенам
      activate neural
      
      neural -> neural : Формирование эмбеддингов
      
      loop пока не найдётся подходящий образ\nиз имеющейся в каталоге одежды
          neural -> db : Поиск одежды по эмбеддингам
          activate db
          alt Такая одежда есть
            db --> neural : Ссылка на товар 
          else
            db --> neural : Ошибка об отсутствии такой одежды
            deactivate db
          end
      end
      
      neural --> web : Описания, изображения и ссылка на товары
      
      deactivate neural
      
      web -> llm : Запрос на описание образов
      llm --> web : Описание образов
    
    deactivate llm
    
    web -> user : Отображение образов и описания к ним
  
  deactivate web

@enduml